version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.3.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm run test -- --ci --reporters=default --reporters=jest-junit
          environment:
            - JEST_JUNIT_OUTPUT_DIR: ./test-results
      - store_test_results:
          path: ./test-results
      - run:
          name: Build
          command: npm run build
  deploy:
    docker:
      - image: circleci/node:14.3.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Save Config
          command: mkdir .vercel && echo $VERCEL_CONFIG > .vercel/project.json
      - run:
          name: Deploy
          command: npm run deploy -- -c --prod --token $VERCEL_TOKEN
workflows:
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context: VERCEL
          filters:
            branches:
              only:
                - master
